presubmits:
- name: presubmit-test-pull
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: docker.io/library/golang:1.17.1-bullseye
      command:
      - /bin/sh
      args:
      - -c
      - go build -tags=json1 -o bin/oc-bundle ./cmd/oc-bundle && 
        chmod +x bin/oc-bundle &&
        mkdir ~/.docker &&
        echo $PULL_SECRET > ~/.docker/config.json &&
        apt update -y && apt install pigz &&
        mkdir $ARTIFACTS/test-create && mkdir $ARTIFACTS/archives && 
        bin/oc-bundle create full --dir=$ARTIFACTS/test-create --output=$ARTIFACTS/archives --config=test/prow/imageset.yaml --log-level=debug && 
#        bin/oc-bundle publish --archive archives --dir test-publish --to-mirror local-reg
postsubmits:
- name: submit-test-build
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: docker.io/library/golang:1.17.1-bullseye
      command:
      - /bin/sh
      args:
      - -c
      - go build -tags=json1 -o bin/oc-bundle ./cmd/oc-bundle 
