presubmits:
- name: presubmit-test-terraform
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: hashicorp/terraform:latest
      command:
      - terraform
      args:
      - -help
postsubmits:
- name: submit-test-terraform
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: hashicorp/terraform:latest
      command:
      - terraform
      args:
      - -help
