presubmits:
- name: presubmit-test-terraform
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: docker.io/library/golang:1.17.1-bullseye
      command:
      - /bin/sh
      args:
      - -c
      - go build -tags=json1 -o bin/oc-bundle ./cmd/oc-bundle && 
        chmod +x bin/oc-bundle &&
        bin/oc-bundle create full --dir=$ARTIFACTS --config=test/prow/imageset.yaml --log-level=debug
postsubmits:
- name: submit-test-terraform
  always_run: true
  decorate: true
  trigger: "(?m)tf test( please)?" # Regexp, see discussion.
  rerun_command: "tf test"  # String, see discussion.
  spec:
    containers:
    - image: docker.io/library/golang:1.17.1-bullseye
      command:
      - /bin/sh
      args:
      - -c
      - go build -tags=json1 -o bin/oc-bundle ./cmd/oc-bundle 
