# This config demonstrates how to mirror a specified
# version(s) of openshift. Optionally, omit the version to mirror
# the latest release.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: stable-4.9
        minVersion: 4.9.13
        maxVersion: 4.9.26