# This config demonstrates how to mirror a single operator. 

# By specifying a minVersion, that version and every version to the
# specified channel's latest (HEAD) version will be mirrored. 

# If a package is specified with no minVersion/maxVersion or channel, each channel's latest
# version in the specified package will be mirrored.

# If the package is specified with a minVersion and maxVersion, all bundles within that range
# will be mirrored.
# WARNING: Any specified channel information will override this setting. Setting versions by
# package or channel are mutually exclusive.
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: elasticsearch-operator
          minVersion: '5.3.2-20'
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: elasticsearch-operator
---
apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
mirror:
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.10
      packages:
        - name: rhacs-operator
          channels:
            - name: stable
              minVersion: '3.67.0'
              maxVersion: '3.67.2'

