# This example demonstrates how to mirror a specific
# okd release. Optionally, omit the version to mirror
# the latest release.
---
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
mirror:
  ocp:
    channels:
      - name: okd
        versions:
        - '4.10.0-0.okd-2022-01-20-011141'
