# This example demonstrates how to mirror a helm chart
# and all referenced images within that chart. A version
# must be specified for the chart.
---
apiVersion: mirror.openshift.io/v1alpha1
kind: ImageSetConfiguration
mirror:
  helm:
    repos:
      - name: podinfo
        url: https://stefanprodan.github.io/podinfo
        charts:
          - name: podinfo
            version: 5.0.0
        