# This config demonstrates the use of `bundles` list for operator catalogs 
# in oder to mirror a selected list of bundles from the catalog image to a 
# different location on the target registry.

# IMPORTANT: `bundles` field is available for oc-mirror v2 only.

# To mirror only v1.1.0 of aws-load-balancer-operator and v0.10.0-mas of 3scale-operator
# from the catalog, use the below ImageSetConfig with the following command:
# $ oc mirror --v2 -c ./ImageSetConfiguration.yml docker://registry.example.com/my-org
kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
mirror:
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.14
    packages:
    - name: aws-load-balancer-operator
      bundles:
      - name: aws-load-balancer-operator.v1.1.0
    - name: 3scale-operator
      bundles:
      - name: 3scale-operator.v0.10.0-mas